export const SET_MUSICSINGER = 'SET_MUSICSINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULLSCREEN_STATE = 'SET_FULLSCREEN_STATE'

export const SET_PLAYLIST_STATE = 'SET_PLAYLIST_STATE'

export const SET_SEQUENCELIST_STATE = 'SET_SEQUENCELIST_STATE'

export const SET_MODE_STATE = 'SET_MODE_STATE'

export const SET_CURRENTINDEX_STATE = 'SET_CURRENTINDEX_STATE'